// ARQUIVO GERADO AUTOMATICAMENTE
// Execute o comando 'yarn build-svg-gallery' para atualizar.

import {
  AccountCircleSvg,
  AddCircleSvg,
  AddSvg,
  AlarmOverviewSvg,
  AlarmsSvg,
  AlertCircleSvg,
  AlertTriangleSvg,
  AllLinesSvg,
  AnalogOutputSvg,
  ArrowCircle,
  ArrowCircleSvg,
  ArrowDropdownSvg,
  ArrowRightSvg,
  ArrowSvg,
  AssignmentLateSvg,
  BackupSvg,
  BellSvg,
  BrushSvg,
  BuildFillSvg,
  BuildSvg,
  BusinessCenterSvg,
  CachedSvg,
  CalendarCheckSvg,
  CalendarDaySvg,
  CalendarWeekSvg,
  CancelSvg,
  CaretSvg,
  ChartsSvg,
  CheckBoxBlankSvg,
  CheckSvg,
  ChevronRightSvg,
  CircleSvg,
  CloseSvg,
  ConverterSvg,
  CopySvg,
  DataUsageSvg,
  DefrostSvg,
  DeleteSvg,
  DescriptionSvg,
  DeviceMaintenanceSvg,
  DeviceSvg,
  DigitalOutputSvg,
  DotSvg,
  DoubleArrowSvg,
  DownloadSvg,
  DvrSvg,
  EditBasicSvg,
  EditSvg,
  EmailSvg,
  EventAvailableSvg,
  EventSvg,
  ExportCSVSvg,
  ExportXLSSvg,
  Filter2Svg,
  FilterNoneSvg,
  FilterOffSvg,
  FilterSvg,
  GavelSvg,
  GearsSvg,
  GraphicReportSvg,
  GroupSvg,
  HelpCircleSvg,
  ImageSvg,
  ImportSvg,
  InfoFillSvg,
  InfoSvg,
  InsertChartSvg,
  InsertDriveFileSvg,
  InsertInvitationSvg,
  InstrumentIconSvg,
  InstrumentSvg,
  LanguageSvg,
  LibraryBooksSvg,
  LineReferenceBothSvg,
  LineReferenceClearSvg,
  LineReferenceHorizontalSvg,
  LineReferenceVerticalSvg,
  LockSvg,
  LogOutSvg,
  MenuSvg,
  MoonSvg,
  MoreHorizontalSvg,
  MoreVerticalSvg,
  NotificationsActiveSvg,
  NotificationsOffSvg,
  OpenInBrowserSvg,
  ParametersSvg,
  PermIdentitySvg,
  PersonAddSvg,
  PictureAsPdfSvg,
  PowerOnOffSvg,
  PrintSvg,
  RadioButtonCheckedSvg,
  RadioButtonUncheckedSvg,
  RefreshSvg,
  RemoveSvg,
  ReplySvg,
  ReportTrendingSvg,
  ResetSvg,
  RestoreSvg,
  SaveSimpleSvg,
  SaveSvg,
  ScheduleSvg,
  SchedulingSvg,
  SearchSvg,
  SelectAllMarkSvg,
  SelectAllSvg,
  SelectNoneSvg,
  SettingsBasicSvg,
  SettingsSvg,
  ShareSvg,
  SiteMapSvg,
  SuccessSvg,
  SunSvg,
  SwapHorizontalExtendSvg,
  SwapHorizontalSvg,
  TemperatureSvg,
  TextFieldsSvg,
  TrashSvg,
  TrendingUpSvg,
  UpdateSvg,
  UsbSvg,
  UserFilledSvg,
  UserSvg,
  VisibilityOffSvg,
  VisibilitySvg,
  WifiSvg,
  WindowRestoreSvg,
  XSvg,
} from '..'

const useSvg = (size: number, color: string | undefined) => {
  const svgArray = [
    {
      name: 'AccountCircleSvg',
      component: <AccountCircleSvg size={size} color={color} />,
    },
    {
      name: 'AddCircleSvg',
      component: <AddCircleSvg size={size} color={color} />,
    },
    { name: 'AddSvg', component: <AddSvg size={size} color={color} /> },
    {
      name: 'AlarmOverviewSvg',
      component: <AlarmOverviewSvg size={size} color={color} />,
    },
    { name: 'AlarmsSvg', component: <AlarmsSvg size={size} color={color} /> },
    {
      name: 'AlertCircleSvg',
      component: <AlertCircleSvg size={size} color={color} />,
    },
    {
      name: 'AlertTriangleSvg',
      component: <AlertTriangleSvg size={size} color={color} />,
    },
    {
      name: 'AllLinesSvg',
      component: <AllLinesSvg size={size} color={color} />,
    },
    {
      name: 'AnalogOutputSvg',
      component: <AnalogOutputSvg size={size} color={color} />,
    },
    {
      name: 'ArrowCircle',
      component: <ArrowCircle size={size} color={color} />,
    },
    {
      name: 'ArrowCircleSvg',
      component: <ArrowCircleSvg size={size} color={color} />,
    },
    {
      name: 'ArrowDropdownSvg',
      component: <ArrowDropdownSvg size={size} color={color} />,
    },
    {
      name: 'ArrowRightSvg',
      component: <ArrowRightSvg size={size} color={color} />,
    },
    { name: 'ArrowSvg', component: <ArrowSvg size={size} color={color} /> },
    {
      name: 'AssignmentLateSvg',
      component: <AssignmentLateSvg size={size} color={color} />,
    },
    { name: 'BackupSvg', component: <BackupSvg size={size} color={color} /> },
    { name: 'BellSvg', component: <BellSvg size={size} color={color} /> },
    { name: 'BrushSvg', component: <BrushSvg size={size} color={color} /> },
    {
      name: 'BuildFillSvg',
      component: <BuildFillSvg size={size} color={color} />,
    },
    { name: 'BuildSvg', component: <BuildSvg size={size} color={color} /> },
    {
      name: 'BusinessCenterSvg',
      component: <BusinessCenterSvg size={size} color={color} />,
    },
    { name: 'CachedSvg', component: <CachedSvg size={size} color={color} /> },
    {
      name: 'CalendarCheckSvg',
      component: <CalendarCheckSvg size={size} color={color} />,
    },
    {
      name: 'CalendarDaySvg',
      component: <CalendarDaySvg size={size} color={color} />,
    },
    {
      name: 'CalendarWeekSvg',
      component: <CalendarWeekSvg size={size} color={color} />,
    },
    { name: 'CancelSvg', component: <CancelSvg size={size} color={color} /> },
    { name: 'CaretSvg', component: <CaretSvg size={size} color={color} /> },
    { name: 'ChartsSvg', component: <ChartsSvg size={size} color={color} /> },
    {
      name: 'CheckBoxBlankSvg',
      component: <CheckBoxBlankSvg size={size} color={color} />,
    },
    { name: 'CheckSvg', component: <CheckSvg size={size} color={color} /> },
    {
      name: 'ChevronRightSvg',
      component: <ChevronRightSvg size={size} color={color} />,
    },
    { name: 'CircleSvg', component: <CircleSvg size={size} color={color} /> },
    { name: 'CloseSvg', component: <CloseSvg size={size} color={color} /> },
    {
      name: 'ConverterSvg',
      component: <ConverterSvg size={size} color={color} />,
    },
    { name: 'CopySvg', component: <CopySvg size={size} color={color} /> },
    {
      name: 'DataUsageSvg',
      component: <DataUsageSvg size={size} color={color} />,
    },
    { name: 'DefrostSvg', component: <DefrostSvg size={size} color={color} /> },
    { name: 'DeleteSvg', component: <DeleteSvg size={size} color={color} /> },
    {
      name: 'DescriptionSvg',
      component: <DescriptionSvg size={size} color={color} />,
    },
    {
      name: 'DeviceMaintenanceSvg',
      component: <DeviceMaintenanceSvg size={size} color={color} />,
    },
    { name: 'DeviceSvg', component: <DeviceSvg size={size} color={color} /> },
    {
      name: 'DigitalOutputSvg',
      component: <DigitalOutputSvg size={size} color={color} />,
    },
    { name: 'DotSvg', component: <DotSvg size={size} color={color} /> },
    {
      name: 'DoubleArrowSvg',
      component: <DoubleArrowSvg size={size} color={color} />,
    },
    {
      name: 'DownloadSvg',
      component: <DownloadSvg size={size} color={color} />,
    },
    { name: 'DvrSvg', component: <DvrSvg size={size} color={color} /> },
    {
      name: 'EditBasicSvg',
      component: <EditBasicSvg size={size} color={color} />,
    },
    { name: 'EditSvg', component: <EditSvg size={size} color={color} /> },
    { name: 'EmailSvg', component: <EmailSvg size={size} color={color} /> },
    {
      name: 'EventAvailableSvg',
      component: <EventAvailableSvg size={size} color={color} />,
    },
    { name: 'EventSvg', component: <EventSvg size={size} color={color} /> },
    {
      name: 'ExportCSVSvg',
      component: <ExportCSVSvg size={size} color={color} />,
    },
    {
      name: 'ExportXLSSvg',
      component: <ExportXLSSvg size={size} color={color} />,
    },
    { name: 'Filter2Svg', component: <Filter2Svg size={size} color={color} /> },
    {
      name: 'FilterNoneSvg',
      component: <FilterNoneSvg size={size} color={color} />,
    },
    {
      name: 'FilterOffSvg',
      component: <FilterOffSvg size={size} color={color} />,
    },
    { name: 'FilterSvg', component: <FilterSvg size={size} color={color} /> },
    { name: 'GavelSvg', component: <GavelSvg size={size} color={color} /> },
    { name: 'GearsSvg', component: <GearsSvg size={size} color={color} /> },
    {
      name: 'GraphicReportSvg',
      component: <GraphicReportSvg size={size} color={color} />,
    },
    { name: 'GroupSvg', component: <GroupSvg size={size} color={color} /> },
    {
      name: 'HelpCircleSvg',
      component: <HelpCircleSvg size={size} color={color} />,
    },
    { name: 'ImageSvg', component: <ImageSvg size={size} color={color} /> },
    { name: 'ImportSvg', component: <ImportSvg size={size} color={color} /> },
    {
      name: 'InfoFillSvg',
      component: <InfoFillSvg size={size} color={color} />,
    },
    { name: 'InfoSvg', component: <InfoSvg size={size} color={color} /> },
    {
      name: 'InsertChartSvg',
      component: <InsertChartSvg size={size} color={color} />,
    },
    {
      name: 'InsertDriveFileSvg',
      component: <InsertDriveFileSvg size={size} color={color} />,
    },
    {
      name: 'InsertInvitationSvg',
      component: <InsertInvitationSvg size={size} color={color} />,
    },
    {
      name: 'InstrumentIconSvg',
      component: <InstrumentIconSvg size={size} color={color} />,
    },
    {
      name: 'InstrumentSvg',
      component: <InstrumentSvg size={size} color={color} />,
    },
    {
      name: 'LanguageSvg',
      component: <LanguageSvg size={size} color={color} />,
    },
    {
      name: 'LibraryBooksSvg',
      component: <LibraryBooksSvg size={size} color={color} />,
    },
    {
      name: 'LineReferenceBothSvg',
      component: <LineReferenceBothSvg size={size} color={color} />,
    },
    {
      name: 'LineReferenceClearSvg',
      component: <LineReferenceClearSvg size={size} color={color} />,
    },
    {
      name: 'LineReferenceHorizontalSvg',
      component: <LineReferenceHorizontalSvg size={size} color={color} />,
    },
    {
      name: 'LineReferenceVerticalSvg',
      component: <LineReferenceVerticalSvg size={size} color={color} />,
    },
    { name: 'LockSvg', component: <LockSvg size={size} color={color} /> },
    { name: 'LogOutSvg', component: <LogOutSvg size={size} color={color} /> },
    { name: 'MenuSvg', component: <MenuSvg size={size} color={color} /> },
    { name: 'MoonSvg', component: <MoonSvg size={size} color={color} /> },
    {
      name: 'MoreHorizontalSvg',
      component: <MoreHorizontalSvg size={size} color={color} />,
    },
    {
      name: 'MoreVerticalSvg',
      component: <MoreVerticalSvg size={size} color={color} />,
    },
    {
      name: 'NotificationsActiveSvg',
      component: <NotificationsActiveSvg size={size} color={color} />,
    },
    {
      name: 'NotificationsOffSvg',
      component: <NotificationsOffSvg size={size} color={color} />,
    },
    {
      name: 'OpenInBrowserSvg',
      component: <OpenInBrowserSvg size={size} color={color} />,
    },
    {
      name: 'ParametersSvg',
      component: <ParametersSvg size={size} color={color} />,
    },
    {
      name: 'PermIdentitySvg',
      component: <PermIdentitySvg size={size} color={color} />,
    },
    {
      name: 'PersonAddSvg',
      component: <PersonAddSvg size={size} color={color} />,
    },
    {
      name: 'PictureAsPdfSvg',
      component: <PictureAsPdfSvg size={size} color={color} />,
    },
    {
      name: 'PowerOnOffSvg',
      component: <PowerOnOffSvg size={size} color={color} />,
    },
    { name: 'PrintSvg', component: <PrintSvg size={size} color={color} /> },
    {
      name: 'RadioButtonCheckedSvg',
      component: <RadioButtonCheckedSvg size={size} color={color} />,
    },
    {
      name: 'RadioButtonUncheckedSvg',
      component: <RadioButtonUncheckedSvg size={size} color={color} />,
    },
    { name: 'RefreshSvg', component: <RefreshSvg size={size} color={color} /> },
    { name: 'RemoveSvg', component: <RemoveSvg size={size} color={color} /> },
    { name: 'ReplySvg', component: <ReplySvg size={size} color={color} /> },
    {
      name: 'ReportTrendingSvg',
      component: <ReportTrendingSvg size={size} color={color} />,
    },
    { name: 'ResetSvg', component: <ResetSvg size={size} color={color} /> },
    { name: 'RestoreSvg', component: <RestoreSvg size={size} color={color} /> },
    {
      name: 'SaveSimpleSvg',
      component: <SaveSimpleSvg size={size} color={color} />,
    },
    { name: 'SaveSvg', component: <SaveSvg size={size} color={color} /> },
    {
      name: 'ScheduleSvg',
      component: <ScheduleSvg size={size} color={color} />,
    },
    {
      name: 'SchedulingSvg',
      component: <SchedulingSvg size={size} color={color} />,
    },
    { name: 'SearchSvg', component: <SearchSvg size={size} color={color} /> },
    {
      name: 'SelectAllMarkSvg',
      component: <SelectAllMarkSvg size={size} color={color} />,
    },
    {
      name: 'SelectAllSvg',
      component: <SelectAllSvg size={size} color={color} />,
    },
    {
      name: 'SelectNoneSvg',
      component: <SelectNoneSvg size={size} color={color} />,
    },
    {
      name: 'SettingsBasicSvg',
      component: <SettingsBasicSvg size={size} color={color} />,
    },
    {
      name: 'SettingsSvg',
      component: <SettingsSvg size={size} color={color} />,
    },
    { name: 'ShareSvg', component: <ShareSvg size={size} color={color} /> },
    { name: 'SiteMapSvg', component: <SiteMapSvg size={size} color={color} /> },
    { name: 'SuccessSvg', component: <SuccessSvg size={size} color={color} /> },
    { name: 'SunSvg', component: <SunSvg size={size} color={color} /> },
    {
      name: 'SwapHorizontalExtendSvg',
      component: <SwapHorizontalExtendSvg size={size} color={color} />,
    },
    {
      name: 'SwapHorizontalSvg',
      component: <SwapHorizontalSvg size={size} color={color} />,
    },
    {
      name: 'TemperatureSvg',
      component: <TemperatureSvg size={size} color={color} />,
    },
    {
      name: 'TextFieldsSvg',
      component: <TextFieldsSvg size={size} color={color} />,
    },
    { name: 'TrashSvg', component: <TrashSvg size={size} color={color} /> },
    {
      name: 'TrendingUpSvg',
      component: <TrendingUpSvg size={size} color={color} />,
    },
    { name: 'UpdateSvg', component: <UpdateSvg size={size} color={color} /> },
    { name: 'UsbSvg', component: <UsbSvg size={size} color={color} /> },
    {
      name: 'UserFilledSvg',
      component: <UserFilledSvg size={size} color={color} />,
    },
    { name: 'UserSvg', component: <UserSvg size={size} color={color} /> },
    {
      name: 'VisibilityOffSvg',
      component: <VisibilityOffSvg size={size} color={color} />,
    },
    {
      name: 'VisibilitySvg',
      component: <VisibilitySvg size={size} color={color} />,
    },
    { name: 'WifiSvg', component: <WifiSvg size={size} color={color} /> },
    {
      name: 'WindowRestoreSvg',
      component: <WindowRestoreSvg size={size} color={color} />,
    },
    { name: 'XSvg', component: <XSvg size={size} color={color} /> },
  ]

  return { svgArray }
}

export default useSvg
